version: '3'

services:
  jsongenius:
    image: semanser/jsongenius
    ports:
      - "3001:8080"
    environment:
      - WS_URL=ws://browserless:3000
      - GIN_MODE=release
      - OPEN_AI_KEY

  browserless:
    image: browserless/chrome
    ports:
      - "3000:3000"
