version: '3'

services:
  rod:
    image: ghcr.io/go-rod/rod

  jsongenius:
    image: semanser/jsongenius:latest
    restart: on-failure
    ports:
      - "3001:8080"
    environment:
      - WS_URL=ws://rod:7317
      - GIN_MODE=release
      - OPEN_AI_KEY
    depends_on:
      - rod
